version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: amrutam-postgres-dev
    environment:
      POSTGRES_DB: amrutam
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7-alpine
    container_name: amrutam-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data

volumes:
  postgres_data_dev:
  redis_data_dev:


